[project]
name = "mcp-sample"
version = "0.1.0"
description = "Sample MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.12.3",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
]
